---
- name: Add HashiCorp GPG key
  become: yes
  shell: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"

- name: Display GPG key fingerprint
  shell: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

- name: Add HashiCorp repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

# - name: Update apt cache
#   become: yes
#   become_method: sudo
#   ansible.builtin.apt:
#     update_cache: yes

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
